# Generated by Django 3.2.5 on 2021-07-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nature_club', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
